package main;
import gui.*;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Main extends javax.swing.JFrame {

    public Main() {
	initComponents();
	setLocationRelativeTo(getParent());

	// Création du panel principal
	fMain = new JPanel(new CardLayout());
	setContentPane(fMain);
	
	// Création de l'InfoCentre
	try {
	    new InfoCentre();
	}
	catch(ClassNotFoundException e) {
	    JOptionPane.showMessageDialog(fMain, new JLabel("Problème Fichier Options"));
	    System.out.println(e.getMessage());
	}
	InfoCentre.initialisation();

	// on ajoute les panels	
	JPanel f1 = new F1_Selection();
	JPanel f2 = new F2_Correction();
	JPanel f3 = new F3_Message();
	JPanel f4 = new F4_Sauvegarde();
	JPanel f5 = new F5_Bilan();
	fMain.add(f1, "f1");
	fMain.add(f2, "f2");
	fMain.add(f3, "f3");
	fMain.add(f4, "f4");
	fMain.add(f5, "f5");

	// on affiche le premier
	cl = (CardLayout)fMain.getLayout();
	cl.first(fMain);

	// Création de l'aiguilleur
	new Aiguilleur(fMain);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        itemNouveau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemQuitter = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();
        itemRepEnreg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tobiacom");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        menuFichier.setText("Fichier");

        itemNouveau.setText("Nouveau");
        itemNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNouveauActionPerformed(evt);
            }
        });
        menuFichier.add(itemNouveau);
        menuFichier.add(jSeparator1);

        itemQuitter.setText("Quitter");
        itemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuitterActionPerformed(evt);
            }
        });
        menuFichier.add(itemQuitter);

        menuBar.add(menuFichier);

        menuOptions.setText("Options");

        itemRepEnreg.setText("Répertoire Enregistrement");
        itemRepEnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRepEnregActionPerformed(evt);
            }
        });
        menuOptions.add(itemRepEnreg);

        menuBar.add(menuOptions);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRepEnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRepEnregActionPerformed
	new F_OptionsEnreg();
    }//GEN-LAST:event_itemRepEnregActionPerformed

    private void itemNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNouveauActionPerformed
	Aiguilleur.aiguillerNouveau();
    }//GEN-LAST:event_itemNouveauActionPerformed

    private void itemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuitterActionPerformed
	System.exit(0);
    }//GEN-LAST:event_itemQuitterActionPerformed

    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
	 * look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	java.awt.EventQueue.invokeLater(new Runnable() {
	    @Override
	    public void run() {
		new Main().setVisible(true);
	    }
	});
    }
    private JPanel fMain;
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemNouveau;
    private javax.swing.JMenuItem itemQuitter;
    private javax.swing.JMenuItem itemRepEnreg;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenu menuOptions;
    // End of variables declaration//GEN-END:variables
}
