package gui;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import main.InfoCentre;

public class F4_Sauvegarde extends javax.swing.JPanel {

    /**
     * 
     */
    public F4_Sauvegarde() {
	initComponents();
    }

    /**
     * 
     */
    public void updatePanel() {
	//
	tfBAN.setText(InfoCentre.getRepBAN() + "/" + InfoCentre.getNomFic() + ".BAN");
	tfETI.setText(InfoCentre.getRepETI() + "/" + InfoCentre.getNomFic() + ".ETI");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        labelBAN = new javax.swing.JLabel();
        tfBAN = new javax.swing.JTextField();
        btBAN = new javax.swing.JButton();
        tfETI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btETI = new javax.swing.JButton();
        btSuivant = new javax.swing.JButton();
        checkBoxEtiquette = new javax.swing.JCheckBox();

        labelTitre.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        labelTitre.setText("Étape #4 - Sauvegarde");

        labelBAN.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelBAN.setText("Sauvegarde du Fichier .BAN");

        btBAN.setText("Enregistrer Sous");
        btBAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBANActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Sauvegarde du Fichier .ETI");

        btETI.setText("Enregistrer Sous");
        btETI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btETIActionPerformed(evt);
            }
        });

        btSuivant.setText("Suivant");
        btSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuivantActionPerformed(evt);
            }
        });

        checkBoxEtiquette.setSelected(true);
        checkBoxEtiquette.setText("Inverser l'ordre des étiquettes");
        checkBoxEtiquette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEtiquetteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btSuivant))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(labelTitre)
                                    .add(layout.createSequentialGroup()
                                        .add(tfBAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 631, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btBAN)))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                                .add(layout.createSequentialGroup()
                                    .add(tfETI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 625, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(12, 12, 12)
                                    .add(btETI)))
                            .add(labelBAN)
                            .add(checkBoxEtiquette))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(labelTitre)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btSuivant))
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(labelBAN)
                        .add(3, 3, 3)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btBAN)
                            .add(tfBAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(40, 40, 40)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(tfETI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btETI))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(checkBoxEtiquette)
                        .add(0, 350, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btBANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBANActionPerformed
	JFileChooser saveFic = new JFileChooser(new File(InfoCentre.getRepBAN()));
	saveFic.setSelectedFile(new File(InfoCentre.getNomFic() + ".BAN"));
	if(saveFic.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
	    String path = saveFic.getSelectedFile().getParent();
	    String ficBAN = saveFic.getSelectedFile().getName();
	    
	    if(!ficBAN.endsWith(".BAN"))
		ficBAN += ".BAN";
	    
	    // fichier sans extension
	    String ficETI = ficBAN.substring(0, ficBAN.lastIndexOf(".")) + ".ETI";
	    
	    
	    tfBAN.setText(path + "/" + ficBAN);
	    tfETI.setText(path + "/" + ficETI);
	}
    }//GEN-LAST:event_btBANActionPerformed

    
    private void btETIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btETIActionPerformed
	JFileChooser saveFic = new JFileChooser(new File(InfoCentre.getRepETI()));
	saveFic.setSelectedFile(new File(InfoCentre.getNomFic() + ".ETI"));
	if(saveFic.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
	    String path   = saveFic.getSelectedFile().getParent();
	    String ficETI = saveFic.getSelectedFile().getName();
	    
	    if(!ficETI.endsWith(".ETI"))
		ficETI += ".ETI";
	    
	    // fichier sans extension
	    String ficBAN = ficETI.substring(0, ficETI.lastIndexOf(".")) + ".ETI";

	    tfETI.setText(path + "/" + ficETI);
	    tfBAN.setText(path + "/" + ficBAN);
	}
    }//GEN-LAST:event_btETIActionPerformed

    private void btSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuivantActionPerformed
	File ficBAN = new File(tfBAN.getText());
	File ficETI = new File(tfETI.getText());

	// erreur si les champs sont vides
	if(tfBAN.getText() == null || tfETI.getText() == null) {
	    JOptionPane.showMessageDialog(this, new JLabel("Les champs ne sont pas tous remplis"));
	}
	// erreur si le répertoire n'existe pas
	if(!(new File(ficBAN.getParent()).isDirectory())) {
	    JOptionPane.showMessageDialog(this, new JLabel("Le répertoire pour le fichier .BAN n'existe pas"));
	}
	// erreur si le répertoire n'existe pas
	else if(!(new File(ficETI.getParent()).isDirectory())) {
	    JOptionPane.showMessageDialog(this, new JLabel("Le répertoire pour le fichier .ETI n'existe pas"));
	}
	// erreur si les chemins sont identiques
	else if(tfBAN.getText().equals(tfETI.getText())) {
	    JOptionPane.showMessageDialog(this, new JLabel("Les chemins des deux fichiers sont identiques"));
	}
	else {
	    boolean ecraser = true;
	    
	    // avertissement si le fichier existe déjà
	    if(new File(tfBAN.getText()).exists()) {
		int reponse = JOptionPane.showConfirmDialog(this, new JLabel("Le fichier .BAN existe déjà. Ecrasez le fichier ?"));
		
		// on écrit les fichiers
		if(reponse != JOptionPane.YES_OPTION) {
		    ecraser = false;
		}
	    }

	    if(ecraser) {
		InfoCentre.setPathFicBAN(tfBAN.getText());
		InfoCentre.setPathFicETI(tfETI.getText());
		InfoCentre.setInverserEtiquette(checkBoxEtiquette.isSelected());

		InfoCentre.miseEnForme();

		try {
		    InfoCentre.ecrireFichier();
		}
		catch(IOException e) {
		    JOptionPane.showMessageDialog(this, 
			new JLabel("<html>Erreur d'écriture du fichier : <br>" + e.getMessage() + "</html>"));
		}

		Aiguilleur.aiguiller();
	    }
	}
    }//GEN-LAST:event_btSuivantActionPerformed

    private void checkBoxEtiquetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxEtiquetteActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_checkBoxEtiquetteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBAN;
    private javax.swing.JButton btETI;
    private javax.swing.JButton btSuivant;
    private javax.swing.JCheckBox checkBoxEtiquette;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBAN;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTextField tfBAN;
    private javax.swing.JTextField tfETI;
    // End of variables declaration//GEN-END:variables
}
